/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    TrustContract: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "initialOwner",
              "type": "address"
            }
          ],
          "stateMutability": "nonpayable",
          "type": "constructor"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "owner",
              "type": "address"
            }
          ],
          "name": "OwnableInvalidOwner",
          "type": "error"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "account",
              "type": "address"
            }
          ],
          "name": "OwnableUnauthorizedAccount",
          "type": "error"
        },
        {
          "inputs": [],
          "name": "ReentrancyGuardReentrantCall",
          "type": "error"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "a0",
              "type": "address"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "a1",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "initialStake",
              "type": "uint256"
            }
          ],
          "name": "ContractCreated",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "uint128",
              "name": "stake0",
              "type": "uint128"
            },
            {
              "indexed": false,
              "internalType": "uint128",
              "name": "stake1",
              "type": "uint128"
            }
          ],
          "name": "ContractActivated",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "by",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "amount",
              "type": "uint256"
            }
          ],
          "name": "StakeAdded",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "yieldAmount",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "totalYield",
              "type": "uint256"
            }
          ],
          "name": "YieldAccrued",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "defector",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "stolen",
              "type": "uint256"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "penalty",
              "type": "uint256"
            }
          ],
          "name": "Defected",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "user",
              "type": "address"
            },
            {
              "indexed": false,
              "internalType": "uint256",
              "name": "penalty",
              "type": "uint256"
            }
          ],
          "name": "Exited",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "bytes32",
              "name": "key",
              "type": "bytes32"
            },
            {
              "indexed": false,
              "internalType": "bool",
              "name": "frozen",
              "type": "bool"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "by",
              "type": "address"
            }
          ],
          "name": "ContractFrozen",
          "type": "event"
        },
        {
          "anonymous": false,
          "inputs": [
            {
              "indexed": true,
              "internalType": "address",
              "name": "previousOwner",
              "type": "address"
            },
            {
              "indexed": true,
              "internalType": "address",
              "name": "newOwner",
              "type": "address"
            }
          ],
          "name": "OwnershipTransferred",
          "type": "event"
        },
        {
          "stateMutability": "nonpayable",
          "type": "fallback"
        },
        {
          "inputs": [],
          "name": "DAILY_YIELD_BPS",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "partner",
              "type": "address"
            }
          ],
          "name": "addStake",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "partner",
              "type": "address"
            }
          ],
          "name": "createContract",
          "outputs": [],
          "stateMutability": "payable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "partner",
              "type": "address"
            }
          ],
          "name": "defect",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "partner",
              "type": "address"
            }
          ],
          "name": "exit",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "a",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "b",
              "type": "address"
            },
            {
              "internalType": "bool",
              "name": "freeze",
              "type": "bool"
            }
          ],
          "name": "freezeContract",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "a",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "b",
              "type": "address"
            }
          ],
          "name": "getContractDetails",
          "outputs": [
            {
              "components": [
                {
                  "internalType": "address",
                  "name": "addr0",
                  "type": "address"
                },
                {
                  "internalType": "address",
                  "name": "addr1",
                  "type": "address"
                },
                {
                  "internalType": "uint128",
                  "name": "stake0",
                  "type": "uint128"
                },
                {
                  "internalType": "uint128",
                  "name": "stake1",
                  "type": "uint128"
                },
                {
                  "internalType": "uint128",
                  "name": "accruedYield",
                  "type": "uint128"
                },
                {
                  "internalType": "bool",
                  "name": "isActive",
                  "type": "bool"
                },
                {
                  "internalType": "bool",
                  "name": "isFrozen",
                  "type": "bool"
                },
                {
                  "internalType": "uint64",
                  "name": "createdAt",
                  "type": "uint64"
                },
                {
                  "internalType": "uint64",
                  "name": "lastYieldUpdate",
                  "type": "uint64"
                }
              ],
              "internalType": "struct ITrustContract.contractView",
              "name": "",
              "type": "tuple"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "a",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "b",
              "type": "address"
            }
          ],
          "name": "getContractKey",
          "outputs": [
            {
              "internalType": "bytes32",
              "name": "",
              "type": "bytes32"
            }
          ],
          "stateMutability": "pure",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "a",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "b",
              "type": "address"
            },
            {
              "internalType": "uint256",
              "name": "futureDays",
              "type": "uint256"
            }
          ],
          "name": "getProjectedYield",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "user",
              "type": "address"
            }
          ],
          "name": "getTrustScore",
          "outputs": [
            {
              "internalType": "uint256",
              "name": "",
              "type": "uint256"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "a",
              "type": "address"
            },
            {
              "internalType": "address",
              "name": "b",
              "type": "address"
            }
          ],
          "name": "isContractFrozen",
          "outputs": [
            {
              "internalType": "bool",
              "name": "",
              "type": "bool"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "owner",
          "outputs": [
            {
              "internalType": "address",
              "name": "",
              "type": "address"
            }
          ],
          "stateMutability": "view",
          "type": "function"
        },
        {
          "inputs": [],
          "name": "renounceOwnership",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "inputs": [
            {
              "internalType": "address",
              "name": "newOwner",
              "type": "address"
            }
          ],
          "name": "transferOwnership",
          "outputs": [],
          "stateMutability": "nonpayable",
          "type": "function"
        },
        {
          "stateMutability": "payable",
          "type": "receive"
        }
      ],
      transactionHash: "0xd6a11d48a73b5fb3258412bdaa98dd2bc133733de48e3d3ec200ee7d0567051b",
    },
  },
} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
